### PR TITLE
feat: add renderCloseButton prop

### PR DESCRIPTION
**Pull request by fabiosantoscode**
This allows us to apply analytics (and other things perhaps!) to the close button.

### CODE REVIEW

**Comment by gcedo** [comment]
Yep, @fabiosantoscode, would you mind provisioning?

**Comment by fabiosantoscode** [comment]
As a matter of fact I would.

I'm just coming through and trying to fix things, and I have to touch about 2 more components to finish this small story I'm working on. Does this mean I have to provision 2 more components? I was under the impression provision was supposed to save time.

**Comment by keithamus** [comment]
> I was under the impression provision was supposed to save time.

The 5 minutes it will take you to tag, document and publish `2.1.0` you could use to simply `npm i @economist/provision-react-component && provision-react-component`.

**Comment by fabiosantoscode** [comment]
Given our team's output lately, I believe it's not a stretch to say that this process takes more than five minutes. And this fix actually needs to go in asap. The business wants to ship the subscription bar. @angelorepole has authorised an unprovisioned merge.

**Pull request merged**
